apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: rakesh
spec:
  selector:
    matchLabels:
      app: rakesh
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: rakesh
    spec:     # pod spec
      containers: 
      - name: customer
        ports:
        - containerPort: 1337
          $patch: delete
        - containerPort: 1337  
        env: 
        - name: DATABASE_NAME
          value: "rakesh"  
   
                  
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: rakesh
spec:
  selector:
    app: rakesh
  ports:
    - port: 1337
      $patch: delete
      targetPort: 1337
      $patch: delete
    - port: 1337
      targetPort: 1337  


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prodcustomer-vs
spec:
  hosts: 
    - rakesh-api.managedorg.io
  http:
    - route:
        - destination:
            host: rakesh-customer-service.default.svc.cluster.local
            port:
              number: 1337
